[package]
name = "nescient"
version = "0.0.0"
authors = ["Isaac Clayton <slightknack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.19"
